# Generated by Django 4.0.3 on 2022-04-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField(verbose_name='Date Published (YYYY-MM-DD)')),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.IntegerField(verbose_name='Number of Pages')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='Cover url')),
                ('language', models.CharField(max_length=2, verbose_name='Publication Language Code')),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
    ]
